"""empty message

Revision ID: a6640168b5a6
Revises: 4c8b0424597c
Create Date: 2019-12-31 13:30:50.102480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6640168b5a6'
down_revision = '4c8b0424597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('destination', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARBINARY(length=1137),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARBINARY(length=1137),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'destination')
    # ### end Alembic commands ###
